language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

branches:
  only:
    - develop 

install:
  - sudo apt-get -qq -y update
  - sudo apt-get install -y qgis python-qgis pylint pep8 
  - pip install -e . --use-mirrors
  - pip install flake8

before_script:
  - echo "Build starting on " `date`

script:
  - make quicktest
  
notifications:
  irc:
    channels:
      - "irc.freenode.org#inasafe"
    use_notice: true
    
  email:
    - tim@kartoza.com
    - akbargumbira@gmail.com
