language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

branches:
  only:
    - develop

-before_install:

install:
  - sudo apt-get -qq -y update
  - sudo apt-get install -y git qgis python-qgis pylint pep8 xvfb python-nose python-coverage pyflakes python-nosexcover python-scientific python-beautifulsoup
  - pip install -e . --use-mirrors
  - pip install flake8
  - echo "Checking out test data " `date`
  - make testdata

before_script:
  - echo "Build starting on " `date`

script:
  - export QGIS_PREFIX_PATH=/usr
  - export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
  - echo "PYTHONPATH: $PYTHONPATH"
  - export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib
  - export INASAFE_POPULATION_PATH=/var/lib/jenkins/jobs/InaSAFE-QGIS2/exposure/population.tif
  - xvfb-run --server-args="-screen 0, 1024x768x24" nosetests -A 'not slow' -v --with-id --with-xcoverage --with-xunit --verbose --cover-package=safe,safe_qgis safe safe_qgis

notifications:
  irc:
    channels:
      - "irc.freenode.org#inasafe"
    use_notice: true

  email:
    - tim@kartoza.com
    - akbargumbira@gmail.com
