services:
    - docker
before_install:
    # Build this docker:
    # - cd qgis-testing-environment && docker build -t qgis-testing-environment .
    # or just pull it:
    - docker pull elpaso/qgis-testing-environment:latest
install:
    - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 elpaso/qgis-testing-environment
    - sleep 10
    # Setup qgis and enable the plugin
    - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh inasafe"
    # If needd additional steps (for example make or paver setup, place it here)
    # Link the plugin to the tests_directory
    - docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory /root/.qgis2/python/plugins/inasafe"

script:
    - docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh test_suite.run_all"

notifications:
  irc:
    channels:
      - "irc.freenode.org#inasafe"
    use_notice: true

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a021ad05fffeac7b0a92L
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always

  email:
    - tim@kartoza.com
    - ismail@kartoza.com
    - rizky@kartoza.com
    - etienne@kartoza.com
